### PR TITLE
Fix GH Actions

### LINKED ISSUE #4: Failing workflows
Hi @AmeerTaweel, just to notify that workflows fail. I don't quite know the cause

### PR DESCRIPTION
**Pull request by deemp**

### CODE REVIEW

**Comment by ameertaweel** [comment]
It seems that we have conflicts. I will look into them and resolve them so we can finalize the merge.

**Comment by deemp** [comment]
@AmeerTaweel, you can just select my versions of files when [merging](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github). I wonder if you'll be able to do so with large files.

**Comment by ameertaweel** [comment]
I think I've done it correctly. We'll see when the action is done...

**Comment by ameertaweel** [comment]
It works as expected! But GitHub didn't understand that I merged this PR and it's still open...

**Comment by deemp** [comment]
Well, it didn't work this time. To clean the history, make `git rebase && git reset --hard HEAD~N && git push -f` where `N` is the number of last commits that you'd like to erase.

**Pull request closed without merging**
